src/Entity/Upload.php
<?php

namespace App\Entity;

use App\Repository\UploadRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UploadRepository::class)]
class Upload
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $orig_name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $upload_date = null;

    #[ORM\ManyToOne(inversedBy: 'uploads')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Key $uploaded_by = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getOrigName(): ?string
    {
        return $this->orig_name;
    }

    public function setOrigName(string $orig_name): static
    {
        $this->orig_name = $orig_name;

        return $this;
    }

    public function getUploadDate(): ?\DateTimeInterface
    {
        return $this->upload_date;
    }

    public function setUploadDate(\DateTimeInterface $upload_date): static
    {
        $this->upload_date = $upload_date;

        return $this;
    }

    public function getUploadedBy(): ?Key
    {
        return $this->uploaded_by;
    }

    public function setUploadedBy(?Key $uploaded_by): static
    {
        $this->uploaded_by = $uploaded_by;

        return $this;
    }
}

src/Controller/PanelController.php
<?php

namespace App\Controller;

use App\Entity\Key;
use App\Entity\Upload;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PanelController extends AbstractController
{
    /**
     *  Define front-ends sidebar links here,
     *  where key is route name and value is the display name
     */
    const PANEL_NAVBAR_MENU = [
        'app_panel_home' => 'Home',
        'app_panel_gallery' => 'Gallery',
        'app_panel_keys' => 'Keys',
        'app_panel_stats' => 'Statistics'
    ];

    #[Route('/', name: 'app_panel_redirect')]
    public function redirectToPanel(): Response
    {
        return $this->redirectToRoute("app_panel_home");
    }

    #[Route('/panel', name: 'app_panel_home')]
    public function home(): Response
    {
        return $this->render('panel/home/home.html.twig', []);
    }

    #[Route('/panel/gallery', name: 'app_panel_gallery')]
    public function gallery(ManagerRegistry $doctrine, Security $security): Response
    {
        $uploads = $doctrine->getRepository(Upload::class)->getUploadsByUserPaginated($security->getUser());

        return $this->render('panel/gallery/gallery.html.twig', ["uploads" => $uploads]);
    }

    #[Route('/panel/keys', name: 'app_panel_keys')]
    public function keys(ManagerRegistry $doctrine, Security $security): Response
    {
        $keys = $doctrine->getRepository(Key::class)->findBy(["generated_by" => $security->getUser()], ["id" => "DESC"]);

        return $this->render('panel/keys/keys.html.twig', [
            "keys" => $keys
        ]);
    }

    #[Route('/panel/stats', name: 'app_panel_stats')]
    public function stats(): Response
    {
        return $this->render('panel/stats/stats.html.twig', []);
    }
}

templates/panel/gallery/gallery.html.twig
{% extends 'panel/base_panel.html.twig' %}

{% block title %}
    {{ parent() }} - Gallery
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .grid div {
            width: 32%;
            padding: 5px;
        }

        .grid div > * {
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    {{ parent() }}

    <div class="col-12 grid">
        {% for upload in uploads %}
            <div>
                <img class="grid-item" src="/{{ upload.name }}" alt="{{ upload.origName }}">
            </div>
        {% endfor %}
    </div>
{% endblock %}

{# TODO: Gallery isn't perfect yet. It starts to bug out once you requests multiple pages fast after each other #}
{% block javascripts_end %}
    {{ parent() }}
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@5/imagesloaded.pkgd.min.js"></script>

    <script>
        const iso = new Isotope( '.grid', {
            // options
            percentPosition: true,
            layoutMode: 'masonry',

        });

        {# Images have been loaded, re-do the masonry layout #}
        imagesLoaded( document.querySelector('.grid'), () => {
            iso.layout()
        });

        {# Infinite Scroll #}
        let page = 1
        let loading = false

        window.addEventListener('scroll', async () => {
            const scrollY = window.scrollY
            const windowHeight = window.innerHeight
            const contentHeight = document.documentElement.scrollHeight

            if(scrollY + windowHeight >= contentHeight - 500) {
                if(loading) return
                else loading = true

                let response = await fetch(`{{ path('api_uploads_get') }}/${page}`)
                let responseJson = await response.json()

                for(const upload of responseJson) {
                    const newDiv = document.createElement("div")
                    newDiv.innerHTML = `
                        <img class="grid-item" src="/${upload.name}" alt="${upload.orig_name}">
                    `
                    iso.insert(newDiv)
                }

                page++
                loading = false
            }
        })
    </script>
{% endblock %}