src/Entity/Key.php
<?php

namespace App\Entity;

use App\Repository\KeyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: KeyRepository::class)]
#[ORM\Table(name: '`key`')]
class Key
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $secret = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\ManyToOne(inversedBy: 'secrets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $generated_by = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $generated_at = null;

    #[ORM\Column]
    private ?bool $allow_images = null;

    #[ORM\Column]
    private ?bool $allow_videos = null;

    #[ORM\Column]
    private ?bool $allow_documents = null;

    #[ORM\Column]
    private ?bool $allow_executables = null;

    #[ORM\OneToMany(mappedBy: 'uploaded_by', targetEntity: Upload::class)]
    private Collection $uploads;

    public function __construct()
    {
        $this->uploads = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSecret(): ?string
    {
        return $this->secret;
    }

    public function setSecret(string $secret): static
    {
        $this->secret = $secret;

        return $this;
    }

    public function getGeneratedBy(): ?User
    {
        return $this->generated_by;
    }

    public function setGeneratedBy(?User $generated_by): static
    {
        $this->generated_by = $generated_by;

        return $this;
    }

    public function getGeneratedAt(): ?\DateTimeInterface
    {
        return $this->generated_at;
    }

    public function setGeneratedAt(\DateTimeInterface $generated_at): static
    {
        $this->generated_at = $generated_at;

        return $this;
    }

    public function isAllowImages(): ?bool
    {
        return $this->allow_images;
    }

    public function setAllowImages(bool $allow_images): static
    {
        $this->allow_images = $allow_images;

        return $this;
    }

    public function isAllowVideos(): ?bool
    {
        return $this->allow_videos;
    }

    public function setAllowVideos(bool $allow_videos): static
    {
        $this->allow_videos = $allow_videos;

        return $this;
    }

    public function isAllowDocuments(): ?bool
    {
        return $this->allow_documents;
    }

    public function setAllowDocuments(bool $allow_documents): static
    {
        $this->allow_documents = $allow_documents;

        return $this;
    }

    public function isAllowExecutables(): ?bool
    {
        return $this->allow_executables;
    }

    public function setAllowExecutables(bool $allow_executables): static
    {
        $this->allow_executables = $allow_executables;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function toArray(): array {
        return [
            "is_active" => $this->is_active,
            "secret" => $this->secret,
            "allow_images" => $this->allow_images,
            "allow_documents" => $this->allow_documents,
            "allow_videos" => $this->allow_videos,
            "allow_executables" => $this->allow_executables,
            "generated_at" => $this->generated_at->getTimestamp(),
            "generated_by" => $this->getGeneratedBy()->getUsername()
        ];
    }

    /**
     * @return Collection<int, Upload>
     */
    public function getUploads(): Collection
    {
        return $this->uploads;
    }

    public function addUpload(Upload $upload): static
    {
        if (!$this->uploads->contains($upload)) {
            $this->uploads->add($upload);
            $upload->setUploadedBy($this);
        }

        return $this;
    }

    public function removeUpload(Upload $upload): static
    {
        if ($this->uploads->removeElement($upload)) {
            // set the owning side to null (unless already changed)
            if ($upload->getUploadedBy() === $this) {
                $upload->setUploadedBy(null);
            }
        }

        return $this;
    }

    public function generate_sharex_conf(string $httpHost): array {
        return [
            "Version" => "15.0.0",
            "Name" => "IMShare",
            "DestinationType" => "ImageUploader, FileUploader",
            "RequestMethod" => "POST",
            "RequestURL" => $httpHost . "/api/file/upload",
            "Headers" => [ "secret" => $this->secret ],
            "Body" => "MultipartFormData",
            "FileFormName" => "file",
            "URL" => $httpHost . "/json:success.filename"
        ];
    }
}

src/Controller/PanelController.php
<?php

namespace App\Controller;

use App\Entity\Key;
use App\Entity\Upload;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PanelController extends AbstractController
{
    /**
     *  Define front-ends sidebar links here,
     *  where key is route name and value is the display name
     */
    const PANEL_NAVBAR_MENU = [
        'app_panel_home' => 'Home',
        'app_panel_gallery' => 'Gallery',
        'app_panel_keys' => 'Keys',
        'app_panel_stats' => 'Statistics'
    ];

    #[Route('/', name: 'app_panel_redirect')]
    public function redirectToPanel(): Response
    {
        return $this->redirectToRoute("app_panel_home");
    }

    #[Route('/panel', name: 'app_panel_home')]
    public function home(): Response
    {
        return $this->render('panel/home/home.html.twig', []);
    }

    #[Route('/panel/gallery', name: 'app_panel_gallery')]
    public function gallery(ManagerRegistry $doctrine, Security $security): Response
    {
        $uploads = $doctrine->getRepository(Upload::class)->getUploadsByUserPaginated($security->getUser());

        return $this->render('panel/gallery/gallery.html.twig', ["uploads" => $uploads]);
    }

    #[Route('/panel/keys', name: 'app_panel_keys')]
    public function keys(ManagerRegistry $doctrine, Security $security): Response
    {
        $keys = $doctrine->getRepository(Key::class)->findBy(["generated_by" => $security->getUser()], ["id" => "DESC"]);

        return $this->render('panel/keys/keys.html.twig', [
            "keys" => $keys
        ]);
    }

    #[Route('/panel/stats', name: 'app_panel_stats')]
    public function stats(): Response
    {
        return $this->render('panel/stats/stats.html.twig', []);
    }
}

templates/panel/keys/keys.html.twig
{% extends 'panel/base_panel.html.twig' %}

{% block title %}
    {{ parent() }} - Keys
{% endblock %}

{% block content %}
    {{ parent() }}
    <div class="col-xl-9">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-key"></i> Secret Codes
            </div>
            <div class="card-body">
                <div class="row">
                    <table id="key-table" class="table">
                        <thead>
                            <tr>
                                <th scope="col">Secret-Key</th>
                                <th scope="col">Images</th>
                                <th scope="col">Videos</th>
                                <th scope="col">Executables</th>
                                <th scope="col">Documents</th>
                                <th scope="col">Active</th>
                                <th scope="col">Configs</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for key in keys %}
                                <tr data-secret-key="{{ key.secret }}">
                                    <td class="secret">{{ key.secret }}</td>
                                    <td class="toggleable" data-field="allow_images"><i class="fas fa-{{ key.allowImages ? "check" : "xmark" }}"></i></td>
                                    <td class="toggleable" data-field="allow_videos"><i class="fas fa-{{ key.allowVideos ? "check" : "xmark" }}"></i></td>
                                    <td class="toggleable" data-field="allow_executables"><i class="fas fa-{{ key.allowExecutables ? "check" : "xmark" }}"></i></td>
                                    <td class="toggleable" data-field="allow_documents"><i class="fas fa-{{ key.allowDocuments ? "check" : "xmark" }}"></i></td>
                                    <td class="toggleable" data-field="is_active"><i class="fas fa-{{ key.isActive ? "check" : "xmark" }}"></i></td>
                                    <td>
                                        <a class="sharex-config" href="{{ path('api_generate_sharex_conf') }}/{{ key.secret }}" download="IMShareConfig_{{ key.secret[:5] }}.sxcu" title="ShareX">
                                            <img src="{{ asset('build/img/uploadapps/sharex.png') }}" height="16" alt="ShareX"/>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="d-flex justify-content-end">
                    <button id="new-key" class="btn btn-success d-flex align-items-center gap-2">
                        <i class="fa fa-plus-square"></i> <span>Create New Key</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3">
        <div class="card">
            <div class="card-header"><i class="fas fa-info"></i> Info</div>
            <div class="card-body">
                <p>
                    In order to upload a file to IMShare using a HTML-POST request you have to target the url <i>....{# TODO #}</i><br>
                    Your request must contain a specific header called <i>secret</i> using the secret-key as the value.<br>
                    Also your body type has to be <i>multipart/form-data</i>
                </p>
                <p>
                    The secret keys permission states are clickable.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts_end %}
    {{ parent() }}

    <script>
        function createKeyRow(key) {
            let placeholder = document.createElement("tbody")

            placeholder.innerHTML = `
                <tr data-secret-key="${key.secret}">
                    <td class="secret">${key.secret}</td>
                    <td class="toggleable" data-field="allow_images"><i class="fas fa-${key.allow_images ? `check` : `xmark`}"></i></td>
                    <td class="toggleable" data-field="allow_videos"><i class="fas fa-${key.allow_videos ? `check` : `xmark`}"></i></td>
                    <td class="toggleable" data-field="allow_executables"><i class="fas fa-${key.allow_executables ? `check` : `xmark`}"></i></td>
                    <td class="toggleable" data-field="allow_documents"><i class="fas fa-${key.allow_documents ? `check` : `xmark`}"></i></td>
                    <td class="toggleable" data-field="is_active"><i class="fas fa-${key.is_active ? `check` : `xmark`}"></i></td>
                    <td>
                        <a class="sharex-config" href="{{ path('api_generate_sharex_conf') }}/${key.secret}" download="IMShareConfig_${key.secret.substring(0,5)}.sxcu" title="ShareX">
                            <img src="{{ asset('build/img/uploadapps/sharex.png') }}" height="16" alt="ShareX"/>
                        </a>
                    </td>
                </tr>
            `

            return placeholder.firstElementChild
        }

        {# [Event Listener] Change permission state of a key #}
        document.addEventListener('click', async function(event) {
            if(!event.target.matches("#key-table tbody td.toggleable i"))
                return

            try {
                let field = event.target.parentNode.getAttribute("data-field");
                let row = event.target.closest("tr")
                let currentlyEnabled = event.target.getAttribute("class").includes("check")

                let data = {}
                data[field] = !currentlyEnabled

                let response = await fetch(`{{ path('api_key_patch') }}/${row.getAttribute("data-secret-key")}`, {
                    method: "PATCH",
                    body: JSON.stringify(data)
                })
                let responseJSON = await response.json()

                row.replaceWith(createKeyRow(responseJSON))
            } catch(e) {
                console.log(e)
                alert("Error when patching a key")
            }
        })

        {# [Event Listener] Create a new key #}
        document.querySelector("#new-key").addEventListener('click', async () => {
            try {
                {# Generate a new key #}
                let response = await fetch("{{ path('api_key_put') }}", {method: 'PUT'})
                let responseJSON = await response.json()

                document.querySelector("#key-table tbody").appendChild(createKeyRow(responseJSON))
            } catch(e) {
                console.log(e)
                alert("Error when generating a key")
            }
        })
    </script>
{% endblock %}